language: cpp
compiler:
  - gcc
  - clang
install:
  - ./autogen.sh
  - mkdir build
  - cd build
  - ../configure
  - make
  - make install
notifications:
  email:
    on_success: change
    on_failure: always
os:
  - linux
  - osx
